import json
import re
from pathlib import Path
from datetime import datetime
from typing import Dict, Optional


class ReplayIndexer:
    # Matches "season 3", "Season 7", "ProLeague Season 8", "s9"
    SEASON_RE = re.compile(r'\bs(?:eason)?\s*\.?\s*(\d+)\b', re.IGNORECASE)
    WEEK_RE = re.compile(r'\bweek\s*(\d+)\b', re.IGNORECASE)
    ROUND_RE = re.compile(r'\bround\s*(\d+)\b', re.IGNORECASE)
    VOL_RE = re.compile(r'\bvol\.?\s*(\d+)\b', re.IGNORECASE)
    YEAR_RE = re.compile(r'(20\d{2})')
    # A group folder like "Group A" / "Group 1", but not the "Group Stage" folder
    GROUP_DIR_RE = re.compile(r'^group\s+(?!stage\b)\w+$', re.IGNORECASE)

    def __init__(self, input_dir: str, output_file: str,
                 manifest_file: Optional[str] = None):
        self.input_dir = Path(input_dir)
        self.output_file = Path(output_file)
        if manifest_file is None:
            manifest_path = self.input_dir / '.sync-manifest.json'
        else:
            manifest_path = Path(manifest_file)
        self.manifest = self._load_manifest(manifest_path)

    def _load_manifest(self, manifest_path: Path) -> Dict[str, Dict]:
        """Map replay path (relative to input_dir, posix) -> Drive metadata.

        Generated by sync_replays.sh from `rclone lsjson -R`. Drive's
        modifiedTime is the only trustworthy replay date: filesystem mtimes
        do not survive git checkouts on CI runners.
        """
        if not manifest_path.exists():
            print(f"Warning: no sync manifest at {manifest_path}; "
                  f"falling back to filesystem mtimes for file_date")
            return {}
        with open(manifest_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        files: Dict[str, Dict] = {}
        for source in data.get('sources', []):
            prefix = source.get('prefix', '').strip('/')
            for entry in source.get('files', []):
                key = f"{prefix}/{entry['Path']}" if prefix else entry['Path']
                files[key] = entry
        return files

    def create_index(self) -> int:
        """Create index of replay files"""
        index = {
            'collection_info': {
                'timestamp': datetime.now().isoformat(),
                'total_replays': 0,
                'total_size': 0,
                'skipped_files': 0,
            },
            'replays': []
        }

        output_filename = self.output_file.name
        for filepath in sorted(self.input_dir.rglob('*.json')):
            if filepath.name == output_filename or filepath.name.startswith('.'):
                continue
            try:
                index['replays'].append(self._process_replay_file(filepath))
            except (json.JSONDecodeError, OSError, UnicodeDecodeError) as e:
                index['collection_info']['skipped_files'] += 1
                print(f"Skipping unreadable replay {filepath}: {e}")

        # Deterministic order so reruns over unchanged data produce
        # byte-identical output (modulo the timestamp line)
        index['replays'].sort(key=lambda r: r['url'])
        index['collection_info']['total_replays'] = len(index['replays'])
        index['collection_info']['total_size'] = sum(
            r['file_size'] for r in index['replays'])

        self._save_index(index)
        return len(index['replays'])

    def _extract_tournament_info(self, rel_path: Path) -> Dict:
        """Extract tournament information from path.

        Matching is case-insensitive and keys off substrings rather than
        exact folder names, so new folder naming conventions in the Drive
        ("draft prep proleague s9", "ProLeague Season 8", future Cup vols)
        categorize without code changes.
        """
        parts = list(rel_path.parts)
        while parts and parts[0] in ('ce_replay_folder', 'CE Replay Folder'):
            parts.pop(0)
        dirs = parts[:-1]
        dirs_lower = ' / '.join(dirs).lower()

        tournament_info = {
            'is_tournament': False,
            'tournament_path': str(rel_path.parent),
            'tournament_name': None,
            'tournament_type': None,
            'season': None,
            'week': None,
            'stage': None,
            'group': None,
            'match_info': None
        }

        if not parts:
            return tournament_info

        season = self._first(self.SEASON_RE, dirs_lower)
        week = self._first(self.WEEK_RE, dirs_lower)
        round_no = self._first(self.ROUND_RE, dirs_lower)

        if 'proleague' in dirs_lower.replace(' ', ''):
            tournament_info.update({
                'is_tournament': True,
                'tournament_type': 'Pro League',
                'tournament_name': 'Pro League',
                'season': season,
                'week': week,
            })
            if 'draft prep' in dirs_lower:
                tournament_info['stage'] = 'Draft Prep'
            match_dir = next(
                (d for d in reversed(dirs) if ' vs ' in d.lower()), None)
            if match_dir:
                tournament_info['match_info'] = match_dir

        elif 'closed event cup' in dirs_lower:
            vol = self._first(self.VOL_RE, dirs_lower)
            tournament_info.update({
                'is_tournament': True,
                'tournament_type': 'Closed Event Cup',
                'tournament_name': (f'Closed Event Cup Vol {vol}'
                                    if vol else 'Closed Event Cup'),
                'season': vol,
            })
            if round_no:
                tournament_info['stage'] = f'Round {round_no}'

        elif ('global littlewargame league' in dirs_lower
                or 'global league' in dirs_lower):
            tournament_info.update({
                'is_tournament': True,
                'tournament_type': 'Global League',
                'tournament_name': 'Global League',
                'season': season,
                'week': week,
            })
            if 'group stage' in dirs_lower:
                tournament_info['stage'] = 'Group Stage'
                group_dir = next(
                    (d for d in dirs if self.GROUP_DIR_RE.match(d)), None)
                if group_dir:
                    tournament_info['group'] = group_dir

        elif 'replaypack' in dirs_lower or 'replay pack' in dirs_lower:
            pack_dir = next(
                (d for d in dirs
                 if 'replaypack' in d.lower() or 'replay pack' in d.lower()),
                None)
            tournament_info.update({
                'is_tournament': False,
                'tournament_type': 'Replay Pack',
                'tournament_name': pack_dir,
            })

        elif 'ravaged nextpatch' in dirs_lower:
            tournament_info.update({
                'is_tournament': True,
                'tournament_type': 'Ravaged Nextpatch',
                'tournament_name': 'Ravaged Nextpatch',
            })
            if round_no:
                tournament_info['stage'] = f'Round {round_no}'

        elif 'lwgfivehundred' in dirs_lower or 'lwg 500' in dirs_lower:
            lwg_dir = next(
                (d for d in dirs if 'lwgfivehundred' in d.lower()
                 or 'lwg 500' in d.lower()), '')
            year = self._first(self.YEAR_RE, lwg_dir)
            tournament_info.update({
                'is_tournament': True,
                'tournament_type': 'LWG500',
                'tournament_name': f'LWG 500 {year}' if year else 'LWG 500',
            })

        elif 'showmatch' in str(rel_path).lower():
            tournament_info.update({
                'is_tournament': False,
                'tournament_type': 'Showmatch',
                'tournament_name': 'Showmatch',
            })

        return tournament_info

    @staticmethod
    def _first(pattern: 're.Pattern', text: str) -> Optional[str]:
        m = pattern.search(text)
        return m.group(1) if m else None

    def _process_replay_file(self, filepath: Path) -> Dict:
        """Process a single replay file"""
        rel_path = filepath.relative_to(self.input_dir)
        remote = self.manifest.get(rel_path.as_posix())

        if remote:
            file_date = remote['ModTime']
            file_size = remote['Size']
        else:
            file_stat = filepath.stat()
            file_date = datetime.fromtimestamp(file_stat.st_mtime).isoformat()
            file_size = file_stat.st_size

        with open(filepath, 'r', encoding='utf-8') as f:
            replay_data = json.load(f)

        # Filter out spectators (team 0)
        active_players = [
            {
                'name': p.get('name'),
                'team': p.get('team'),
                'clan': p.get('clan')
            }
            for p in replay_data.get('players', [])
            if p.get('team', 0) != 0  # Only include non-spectators
        ]

        return {
            'filename': filepath.name,
            'url': rel_path.as_posix(),
            'file_date': file_date,
            'file_size': file_size,
            'map': replay_data.get('map'),
            'players': active_players,
            'game_version': replay_data.get('gameVersion'),
            'tournament_info': self._extract_tournament_info(rel_path)
        }

    def _save_index(self, index: Dict) -> None:
        """Save index to file"""
        with open(self.output_file, 'w', encoding='utf-8') as f:
            json.dump(index, f, indent=2)


def main():
    """CLI entry point"""
    import argparse
    parser = argparse.ArgumentParser(description='Index LWG replay files')
    parser.add_argument('input_dir', help='Directory containing replay files')
    parser.add_argument('output_file', help='Output index file path')
    parser.add_argument('--manifest', default=None,
                        help='Sync manifest path (default: '
                             '<input_dir>/.sync-manifest.json)')
    args = parser.parse_args()

    indexer = ReplayIndexer(args.input_dir, args.output_file, args.manifest)
    count = indexer.create_index()
    print(f"Processed {count} replay files")


if __name__ == "__main__":
    main()
