name: Sync and Index Replays

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:


permissions:
  contents: write 
  pages: write   
  id-token: write 

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    container: 
      image: rclone/rclone:latest
      options: --user root
    outputs:
      changes_detected: ${{ steps.check.outputs.changes_detected }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup scripts
        run: |
          ls -la
          pwd
          # Install required tools
          apk add --no-cache bash
          chmod +x .github/gha_scripts/*

      - name: Setup rclone
        env:
          RCLONE_SERVICE_ACCOUNT: ${{ secrets.RCLONE_SERVICE_ACCOUNT }}
        shell: bash
        run: |
          pwd
          ls -la
          bash .github/gha_scripts/setup_rclone.sh

      - name: Check for changes
        id: check
        shell: bash
        run: |
          set -x
          echo "Testing rclone configuration..."
          rclone --config=$GITHUB_WORKSPACE/.rclone/rclone.conf config show
          echo "Testing rclone access..."
          rclone --config=$GITHUB_WORKSPACE/.rclone/rclone.conf ls "lwg_replays_by_ce:"
          rclone --config=$GITHUB_WORKSPACE/.rclone/rclone.conf lsd "lwg_replays_by_ce:"
          echo "Running sync check..."
          bash .github/gha_scripts/check_and_sync.sh

      - name: Archive replays with timestamps
        if: steps.check.outputs.changes_detected == 'true'
        run: |
          cd docs
          tar -czf replays.tar.gz replays/
          ls -la replays.tar.gz

      - name: Upload archive
        if: steps.check.outputs.changes_detected == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: replays-archive
          path: docs/replays.tar.gz
          if-no-files-found: error

  process-and-index:
    needs: check-for-changes
    if: needs.check-for-changes.outputs.changes_detected == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Download archive
        uses: actions/download-artifact@v4
        with:
          name: replays-archive
          path: docs/

      - name: Extract archive
        run: |
          cd docs
          tar -xzf replays.tar.gz
          rm replays.tar.gz
          # Debug timestamps
          find replays/ -type f -exec stat -c '%n: %y' {} \;

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          chmod +x .github/gha_scripts/setup_poetry.sh
          .github/gha_scripts/setup_poetry.sh

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "=== Repository Status Before Commit ==="
          ls -la
          echo -e "\n=== Git Configuration ==="
          git config --list
          echo -e "\n=== Running Commit Script ==="
          chmod +x .github/gha_scripts/commit_changes.sh
          .github/gha_scripts/commit_changes.sh

      - name: Trigger GitHub Pages rebuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x .github/gha_scripts/trigger_pages.sh
          .github/gha_scripts/trigger_pages.sh
